To Do List/topro/toappp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home),
    path('emp/', views.emp),
    path('show/', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

To Do List/topro/topro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toappp.urls'))
]

To Do List/topro/toappp/models.py
from django.db import models

class to_do_list(models.Model):
    Sr_No = models.IntegerField()
    name = models.CharField(max_length=20)
    category = models.CharField(max_length=20)
    description = models.TextField(max_length=100)
    date = models.DateTimeField()

    class Meta:
        db_table = "employee"

To Do List/topro/toappp/forms.py
from django import forms
from .models import to_do_list


class to_do_Form(forms.ModelForm):
    class Meta:
        model = to_do_list
        fields = "__all__"

To Do List/topro/toappp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import to_do_Form
from .models import to_do_list


def home(request):
    return HttpResponse(f'<body style="background-color:blue"><div style="text-align:center;'
                        f'color:red;'
                        f'padding-top: 40vh;'
                        f'margin: 0;'
                        f' "><h1>To-Do List</h1></div></body>')


def emp(request):
    if request.method == "POST":
        form = to_do_Form(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = to_do_Form()
    return render(request, 'index.html', {'form': form})


def show(request):
    employees = to_do_list.objects.all()
    return render(request, "show.html", {'employees': employees})


def edit(request, id):
    employee = to_do_list.objects.get(id=id)
    return render(request, 'edit.html', {'employee': employee})


def update(request, id):
    employee = to_do_list.objects.get(id=id)
    form = to_do_Form(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})


def destroy(request, id):
    employee = to_do_list.objects.get(id=id)
    employee.delete()
    return redirect("/show")

To Do List/topro/toappp/templates/edit.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{ employee.id }}">
        {% csrf_token %}
    <div class="container">
<br>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
      <h3>Update Details</h3>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Sr_No:</label>
    <div class="col-sm-4">
        <input type="number" name="Sr_No" id="id_Sr_No" required maxlength="20" value="{{ employee.Sr_No }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Name:</label>
    <div class="col-sm-4">
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">category:</label>
    <div class="col-sm-4">
        <input type="text" name="category" id="id_category" required maxlength="254" value="{{ employee.category }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description:</label>
    <div class="col-sm-4">
        <input type="text" name="description" id="id_description" required maxlength="15" value="{{ employee.description }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date:</label>
    <div class="col-sm-4">
        <input type="date" name="date" id="id_date" required maxlength="15" value="{{ employee.date }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
      <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

To Do List/topro/toappp/templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Sr_No:</label>
    <div class="col-sm-4">
      {{ form.Sr_No }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Name:</label>
    <div class="col-sm-4">
      {{ form.name }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Category:</label>
    <div class="col-sm-4">
      {{ form.category }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description:</label>
    <div class="col-sm-4">
      {{ form.description }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Date:</label>
    <div class="col-sm-4">
      {{ form.date }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

To Do List/topro/toappp/templates/show.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Sr_No</th>
        <th>Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>Date</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.Sr_No }}</td>
        <td>{{ employee.name }}</td>
        <td>{{ employee.category }}</td>
        <td>{{ employee.description }}</td>
        <td>{{ employee.date }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>